/*
SELECT DISTINCT CAR_ID 
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS C 
WHERE C.CAR_ID NOT IN 
(
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE START_DATE <= "2022-10-16" && "2022-10-16"<=END_DATE
)
*/
SELECT CAR_ID,
CASE
WHEN CAR_ID IN
(SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE START_DATE <= "2022-10-16" && "2022-10-16"<=END_DATE
)THEN '대여중'
ELSE '대여 가능'
END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
GROUP BY CAR_ID
ORDER BY CAR_ID DESC 

    


/*
    2022/10/16 -> 대여중인지 아닌지, 이날에 반납해도 대여중임
*/