

WITH A AS(
SELECT WRITER_ID, SUM(PRICE) AS PR
FROM USED_GOODS_BOARD 
WHERE STATUS = 'DONE'
GROUP BY WRITER_ID
HAVING SUM(PRICE) >= 700000
)
SELECT B.USER_ID, B.NICKNAME, A.PR AS TOTAL_SALES
FROM A
JOIN USED_GOODS_USER AS B
ON A.WRITER_ID = B.USER_ID
ORDER BY A.PR