WITH A AS(
SELECT EMP_NO, AVG(SCORE) AS SCORE
FROM HR_GRADE 
GROUP BY EMP_NO
),
B AS(
SELECT H.EMP_NO, A.SCORE
FROM HR_GRADE H
JOIN A
ON H.EMP_NO = A.EMP_NO
GROUP BY H.EMP_NO
)
SELECT B.EMP_NO,H.EMP_NAME,
CASE
    WHEN B.SCORE >=96 THEN 'S'
    WHEN B.SCORE >=90 THEN 'A'
    WHEN B.SCORE >=80 THEN 'B'
    ELSE 'C'
END AS GRADE,
CASE
    WHEN B.SCORE >=96 THEN H.SAL*0.2
    WHEN B.SCORE >=90 THEN H.SAL*0.15
    WHEN B.SCORE >=80 THEN H.SAL*0.1
    ELSE 0
END AS BONUS
FROM B  
JOIN HR_EMPLOYEES H 
ON B.EMP_NO = H.EMP_NO
ORDER BY EMP_NO
/*
SELECT EMP_NO,
CASE
    WHEN SCORE>= 96 THEN 'S'
    WHEN SCORE>= 90 THEN 'A'
    WHEN SCORE>= 80 THEN 'B'
    ELSE 'S'
END AS BONUS_GRADE    
FROM HR_GRADE
*/