/*
    A->5회이상 빌린 차 ID
    B->A.ID 랑 똑같은거 찾기 단 빌린날짜 생각해서
    
SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM B
GROUP BY MONTH(START_DATE), CAR_ID
ORDER BY MONTH(START_DATE) ASC, CAR_ID DESC
    
    
*/


WITH A AS(
SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE START_DATE >= '2022-08-01' AND START_DATE <= '2022-10-31'
GROUP BY CAR_ID 
HAVING COUNT(*) >=5
), B AS(
SELECT C.CAR_ID,C.START_DATE
FROM A
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS C
ON A.CAR_ID = C.CAR_ID
WHERE C.START_DATE >= '2022-08-01' AND C.START_DATE <= '2022-10-31'
ORDER BY C.CAR_ID
)
SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM B
GROUP BY MONTH(START_DATE), CAR_ID
ORDER BY MONTH(START_DATE) ASC, CAR_ID DESC