/*


SELECT B.CATEGORY,SUM(A.SALES) AS TOTAL_SALES
FROM A
JOIN B
ON B.BOOK_ID = A.BOOK_ID
GROUP BY CATEGORY
ORDER BY CATEGORY
*/

WITH A AS(
SELECT SUM(SALES) AS CNT,BOOK_ID
FROM BOOK_SALES
WHERE SALES_DATE >= '2022-01-01' AND SALES_DATE <= '2022-01-31'
GROUP BY book_id
ORDER BY book_id
),
B AS(
SELECT BOOK_ID, CATEGORY
FROM BOOK
)
SELECT B.CATEGORY,SUM(A.CNT) AS TOTAL_SALES
FROM A
JOIN B
ON B.BOOK_ID = A.BOOK_ID
GROUP BY CATEGORY
ORDER BY CATEGORY